### PR TITLE
ESM-compatible exports

### LINKED ISSUE #153: Breakage when running as ESM
Hello, I am trying to move away from old CJS in my project to the more modern ESM. Unfortunately, this module seems to break when running as ESM.

```ts
import * as jsonfile from "jsonfile"

const obj = jsonfile.readFileSync("./config.json");
console.log(JSON.stringify(obj, null, 4));
```

When I have `"type": "commonjs"` in my `package.json`, this file runs as expected. However, after switching to `"type": "module"` in my `package.json`, I get an error:

```console
user@localhost:~/path/to/project $ tsx src/test.ts
file:///C:/path/to/project/test.ts:1
import*as jsonfile from"jsonfile";const obj=jsonfile.readFileSync("./config.json");console.log(JSON.stringify(obj,null,4));
                                                     ^
TypeError: jsonfile.readFileSync is not a function
    at file:///C:/path/to/project/test.ts:1:54
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12)

Node.js v21.7.1
```

This also happens when I `tsc` and `node build/test.js`.

I would love to be able to move to ESM, right now this module is the only thing stopping me (I tried to use raw `JSON.parse` and while that works, it would be nice if this module was usable with ESM).

Thanks in advance.

### PR DESCRIPTION
**Pull request by joshkel**
Node.js handles ESM-CJS interoperability by using its [cjs-module-lexer](https://github.com/nodejs/cjs-module-lexer) to parse CJS files and turn their exports into named exports.  cjs-module-lexer is deliberately limited in its capabilities.  Switching export styles makes jsonfile's exports recognizable by cjs-module-lexer so that ESM code such aborts

```
import { readFileSync } from 'jsonfile'
```

can work as expected, without having to change jsonfile itself to ESM.

Fixes #153

### CODE REVIEW

**Comment by joshkel** [comment]
To demonstrate / test this locally, create a file, `test.mjs`:

```js
import { readFileSync } from './index.js';
console.log(readFileSync('./package.json'));
```

Then run it with and without this change.

File: index.js [hunk 1]
```diff
@@ -78,11 +78,9 @@ function writeFileSync (file, obj, options = {}) {
   return fs.writeFileSync(file, str, options)
 }
 
-const jsonfile = {
+module.exports = {
```
Comment (RyanZim) [inline index.js:83]: Let's add a comment here so this doesn't get accidentally broken in the future
```suggestion
// NOTE: do not change this export format; required for ESM compat
// see https://github.com/jprichardson/node-jsonfile/pull/162 for details
module.exports = {
```

**Review by RyanZim — APPROVED** [review]
LGTM

**Comment by RyanZim** [comment]
Thanks @joshkel! Will try to release sometime next week (I don't like releasing popular libraries on weekends).

**Comment by RyanZim** [comment]
Published as v6.2.0 :tada:

**Comment by joshkel** [comment]
Thanks, @RyanZim!
